#![allow(non_camel_case_types)]

pub mod access;
pub mod archctl;
pub mod dirent;
pub mod drm;
pub mod epoll;
pub mod errno;
pub mod fcntl;
pub mod input;
pub mod ioctls;
pub mod limits;
pub mod mman;
pub mod mount;
pub mod poll;
pub mod reboot;
pub mod resource;
pub mod signal;
pub mod socket;
pub mod stat;
pub mod statvfs;
pub mod termios;
pub mod time;
pub mod uio;
pub mod utsname;
pub mod wait;

pub type off_t = isize;
pub type off64_t = isize;
pub type blksize_t = usize;
pub type blkcnt_t = usize;
pub type clockid_t = usize;
pub type dev_t = usize;
pub type gid_t = u32;
pub type ino_t = usize;
pub type mode_t = u32;
pub type nlink_t = usize;
pub type pid_t = i32;
pub type rlim_t = usize;
pub type uid_t = u32;
pub type fsblkcnt_t = usize;
pub type fsfilcnt_t = usize;
pub type pthread_attr_t = usize;
