#pragma once

typedef enum {
    ZN_SYSCALL_LOG,
    ZN_SYSCALL_ARCHCTL,
    ZN_SYSCALL_PAGE_SIZE,

    ZN_SYSCALL_HANDLE_VALIDATE,
    ZN_SYSCALL_HANDLE_DROP,
    ZN_SYSCALL_HANDLE_CLONE,

    ZN_SYSCALL_VAS_CREATE,

    ZN_SYSCALL_VMO_CREATE,
    ZN_SYSCALL_VMO_CREATE_PHYS,
    ZN_SYSCALL_VMO_MAP,

    ZN_SYSCALL_CHANNEL_CREATE,
    ZN_SYSCALL_CHANNEL_WAIT,
    ZN_SYSCALL_CHANNEL_READ,
    ZN_SYSCALL_CHANNEL_WRITE,

    ZN_SYSCALL_THREAD_CREATE,
    ZN_SYSCALL_THREAD_START,
    ZN_SYSCALL_THREAD_EXIT,

    ZN_SYSCALL_RANDOM_GET,
    ZN_SYSCALL_RANDOM_ENTROPY,
} zn_syscall_t;
